//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cursor_H
#define METASPRITE_cursor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cursor_TILE_ORIGIN 100
#define cursor_TILE_W 8
#define cursor_TILE_H 8
#define cursor_WIDTH 16
#define cursor_HEIGHT 16
#define cursor_TILE_COUNT 6
#define cursor_PALETTE_COUNT 1
#define cursor_COLORS_PER_PALETTE 4
#define cursor_TOTAL_COLORS 4
#define cursor_PIVOT_X 0
#define cursor_PIVOT_Y 0
#define cursor_PIVOT_W 16
#define cursor_PIVOT_H 16
extern const metasprite_t* const cursor_metasprites[3];

BANKREF_EXTERN(cursor)

extern const palette_color_t cursor_palettes[4];
extern const uint8_t cursor_tiles[96];

#endif
