//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dude_H
#define METASPRITE_dude_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dude_TILE_ORIGIN 0
#define dude_TILE_W 8
#define dude_TILE_H 16
#define dude_WIDTH 16
#define dude_HEIGHT 16
#define dude_TILE_COUNT 4
#define dude_PALETTE_COUNT 1
#define dude_COLORS_PER_PALETTE 4
#define dude_TOTAL_COLORS 4
#define dude_PIVOT_X 8
#define dude_PIVOT_Y 8
#define dude_PIVOT_W 16
#define dude_PIVOT_H 16
extern const metasprite_t* const dude_metasprites[1];

BANKREF_EXTERN(dude)

extern const palette_color_t dude_palettes[4];
extern const uint8_t dude_tiles[64];

#endif
