//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frames_H
#define METASPRITE_frames_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frames_TILE_ORIGIN 192
#define frames_TILE_W 8
#define frames_TILE_H 8
#define frames_WIDTH 32
#define frames_HEIGHT 32
#define frames_TILE_COUNT 4
#define frames_PALETTE_COUNT 1
#define frames_COLORS_PER_PALETTE 4
#define frames_TOTAL_COLORS 4

BANKREF_EXTERN(frames)

extern const palette_color_t frames_palettes[4];
extern const uint8_t frames_tiles[64];

#endif
