//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ruins_H
#define METASPRITE_ruins_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ruins_TILE_ORIGIN 0
#define ruins_TILE_W 8
#define ruins_TILE_H 8
#define ruins_WIDTH 160
#define ruins_HEIGHT 144
#define ruins_TILE_COUNT 112
#define ruins_PALETTE_COUNT 5
#define ruins_COLORS_PER_PALETTE 4
#define ruins_TOTAL_COLORS 20
#define ruins_MAP_ATTRIBUTES ruins_map_attributes
#define ruins_MAP_ATTRIBUTES_WIDTH 20
#define ruins_MAP_ATTRIBUTES_HEIGHT 18
#define ruins_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define ruins_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char ruins_map[360];
extern const unsigned char ruins_map_attributes[360];

BANKREF_EXTERN(ruins)

extern const palette_color_t ruins_palettes[20];
extern const uint8_t ruins_tiles[1792];

#endif
