//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ui_tiles_H
#define METASPRITE_ui_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ui_tiles_TILE_ORIGIN 13
#define ui_tiles_TILE_W 8
#define ui_tiles_TILE_H 8
#define ui_tiles_WIDTH 208
#define ui_tiles_HEIGHT 32
#define ui_tiles_TILE_COUNT 104
#define ui_tiles_PALETTE_COUNT 2
#define ui_tiles_COLORS_PER_PALETTE 4
#define ui_tiles_TOTAL_COLORS 8

BANKREF_EXTERN(ui_tiles)

extern const palette_color_t ui_tiles_palettes[8];
extern const uint8_t ui_tiles_tiles[1664];

#endif
